=head1 Info

=head1 Prepare source code

 mkdir ~/devel
 cd ~/devel
 
 git clone git://github.com/mj41/AIAnts.git aiants
 git clone git://github.com/aichallenge/aichallenge.git aichallenge
 
 cd ~/devel/aiants

=head2 Run tests

 prove
 
=head2 Run simple test

 ./utils/run-test.sh

=head2 Run game locally

Run max 30 turns MyBot.pm vs. python/GreedyBot.py on maze_02p_02 map

 ./utils/run-local.sh 30

Run max 500 turns MyBot.pm vs. bots/RandomBot.pm

 ./utils/run-local.sh 500 bots/RandomBot.pm

=head2 Use example bot

 git status -- MyBot.pm
 git diff MyBot.pm
 rm MyBot.pm
 ./utils/use-example-bot.sh bots/RandomBot.pm

=head1 Upload

=head2 Required modules

 cpanm Archive::Zip
 cpanm File::Slurp

=head2 Config example

Create user account, verify account and save your credential to config file.
 
 cat ~/.aibots.cred

 myLogin
 mySecretPasswd

 vim ~/.aibots.cred
 chmod go-rwx ~/.aibots.cred
 touch ~/.aibots.cookies
 chmod go-rwx ~/.aibots.cookies
 
=head2 Upload

 perl util/upload.pl
 perl util/upload.pl up

=head1 Join us

=head2 Commit bit

Join us on irc://irc.freenode.net/perl-ai and ask for commit bit or write directly
to aiants@mj41.cz . You are welcome.

=cut
