=head1 Info

=head2 Run tests

 prove
 
=head2 Run empty bot

 mkdir temp
 cp bots/01-empty.pm MyBot.pm

 perl MyBot.pl temp/output-log.txt 10 t/data/game-web.txt
 less temp/output-log.txt

=head2 Run game locally

 mkdir aichallenge
 git clone git://github.com/aichallenge/aichallenge.git aichallenge
 cd aichallenge/ants
 ./playgame.py --player_seed 42 --end_wait=0.25 --verbose --log_dir game_logs -R -S -I -O -E  --turns 1000 --map_file maps/maze/maze_02p_02.map 'perl ../../MyBot.pl temp/game-out.txt' "python dist/sample_bots/python/GreedyBot.py"
 cat game_logs/0.bot0.error && cat ../../temp/game-out.txt

=cut

=head1 Upload

=head2 Config example

 cat ~/.aibots.cred
 
 myLogin
 mySecretPasswd

 vim ~/.aibots.cred
 chmod go-rwx ~/.aibots.cred
 touch ~/.aibots.cookies
 chmod go-rwx ~/.aibots.cookies
 
=head2 Required modules

 cpanm Archive::Zip

=head2 Upload

 perl util/upload.pl
 perl util/upload.pl up

=cut
