=head1 Info

=head1 Prepare source code

 mkdir ~/devel
 mkdir ~/devel/aiants
 cd ~/devel/aiants
 
 git clone git://github.com/mj41/AIAnts.git .
 git clone git://github.com/aichallenge/aichallenge.git aichallenge

=head2 Run tests

 prove
 
=head2 Run simple test

 ./utils/run-test.sh

=head2 Run game locally

 ./utils/run-local.sh 50

=head2 Use example bot

 git status -- MyBot.pm
 git diff MyBot.pm
 rm MyBot.pm
 ./utils/user-example-bot.sh bots/02-random.pm

=head1 Upload

=head2 Required modules

 cpanm Archive::Zip

=head2 Config example

Create user account, verify account and save your credential to config file.
 
 cat ~/.aibots.cred

 myLogin
 mySecretPasswd

 vim ~/.aibots.cred
 chmod go-rwx ~/.aibots.cred
 touch ~/.aibots.cookies
 chmod go-rwx ~/.aibots.cookies
 
=head2 Upload

 perl util/upload.pl
 perl util/upload.pl up

=head1 Join us

=head2 Commit bit

Join us on irc://irc.freenode.net/perl-ai and ask for commit bit or write directly
to aiants@mj41.cz . You are welcome.

=cut
